# Generated by Django 3.2.12 on 2023-02-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_another'),
    ]

    operations = [
        migrations.CreateModel(
            name='Some',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some', models.CharField(max_length=100)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
            ],
        ),
    ]
